exports.GENRES = [
  { id: 1, name: 'Action' },
  { id: 2, name: 'Thriller' },
  { id: 3, name: 'Crime drama' },
  { id: 4, name: 'Mystery' },
  { id: 5, name: 'Children' },
  { id: 6, name: 'Comedy' },
  { id: 7, name: 'Adventure' },
  { id: 8, name: 'Animated' },
  { id: 9, name: 'Drama' },
  { id: 10, name: 'Comedy drama' },
  { id: 11, name: 'Western' },
  { id: 12, name: 'Historical drama' },
  { id: 13, name: 'Biography' },
  { id: 14, name: 'Horror' },
  { id: 15, name: 'Fantasy' },
  { id: 16, name: 'Dark comedy' },
  { id: 17, name: 'Science fiction' },
];
